# -*- coding: utf-8 -*-
"""ATM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SzYpoIm2sXERHpq-pXJzVC5cNplIhB7x

ATM Simulator Assignment is written in Python. The Assignment file contains a python
script (atm.py). This is a simple console-based system which is very easy to use. Talking
about the system, it contains various functions which include View Balance, Withdrawing,
Depositing amount, and changing the pin. Here, at first, the user has to enter an existing
username, when the username matches the system proceed toward the next procedure i.e
asking for a password/pin number. When a user passes all these sign-in procedures,
he/she can use all those features. It is too easy to use, he/she can check their respective
account statements, Deposit, and Withdrawing as well.

While the user forgot the password on login you have to create a forgot password
functionality.

And forgot password on based on stored email address. If the user type coreect email then
you have to give a prompt for new password.

While depositing or withdrawing an amount, he/she just has to enter the amount then the
system calculates the total remaining balance of the respective account and displays to the
user. And the user can view all these transactions from the account statement. In this ATM
Simulator, the user can also change the password/pin number. For this, the user has to
enter the New pin code and then confirm it in order to change the pin code. This simple
console-based ATM simulator provides the simple account balance management of a
respective account. It contains all the essential features. There is no database connection
or neither any external text nor other files used in this mini Assignment to save the user’s
data. Everything is set inside the source code whether its password/pin code or the
amount.

Functality:

1. Login
2. Sign Up
3. Exit
4. Withdrawl 
5. Deposit 
6. View Balance
7. Password Change
8. Forgot password

ToDOs
"""

# DONE: The Assignment file contains a python script (atm.py). 
# DONE: The system contains various functions which include View Balance, Withdrawing, Depositing amount, and changing the pin. 
# DONE: The user has to enter an existing username, 
# DONE: when the username matches the system proceed toward the next procedure i.e asking for a password/pin number. 
# DONE: While the user forgot the password on login you have to create a forgot password functionality.
# DONE: And forgot password on based on stored email address. If the user type correct email then you have to give a prompt for new password.
# DONE: When a user passes all these sign-in procedures, 
# DONE: he/she can use all those features: View Balance, Withdrawing, Depositing amount, and changing the pin. 
# DONE: he/she can check their respective account statements, Deposit, and Withdrawing as well.
# DONE: While depositing or withdrawing an amount, he/she just has to enter the amount then the system calculates the total remaining balance of the respective account and displays to the user. 
# DONE: And the user can view all these transactions from the account statement. 
# DONE: the user can also change the password/pin number. For this, the user has to enter the New pin code and then confirm it in order to change the pin code. 
# DONE: This simple console-based ATM simulator provides the simple account balance management of a respective account.

database = {
    'username_1':{
        'name' : 'user 1',
        'age': 24,
        'email': 'user_1@gmail.com',
        'password': 'user1',
        'balance' : 1000
    },
    'username_2':{
        'name' : 'user 2',
        'age': 24,
        'email': 'user_2@yahoo.com',
        'password': 'user2',
        'balance' : 1000
    },
    'username_3':{
        'name' : 'user 3',
        'age': 24,
        'email': 'user_3@outlook.com',
        'password': 'user3',
        'balance' : 1000
    },'username_4':{
        'name' : 'user 4',
        'age': 24,
        'email': 'user_4@gmail.com',
        'password': 'user4',
        'balance' : 1000
    }
}

def login(usern, password):
  while usern not in database or database[usern]['password'] != password:
    usern = input('Please enter your correct username: ')
    password =input('please enter your corresponding password: ')
    forgot = input('Forgot password? Y/N: ')
    if forgot == 'Y' or forgot == 'y':
      email = input('Enter your email: ')
      passwordChange(usern, email)
  print('Welcome!')
  return usern

def signUp():
  username = 'username_1'
  while username in database:
    username = input('Choose username that is not taken: ')

  name = input('Enter your name: ')
  age = int(input('Enter your age: '))
  email = input('Enter your email: ')
  password = input('Choose a strong password: ')

  database[username] = {
      'name' : name,
      'age' : age,
      'email' : email,
      'password' : password,
      'balance' : 1000
  }

  print('Congratulations! New account created.')

def withdrawal(user):
  amount = int(input('Enter amount to withdraw'))
  if (amount > database[user]['balance']):
    print("Sorry, currently you don't have sufficient balance.")
  else:
    database[user]['balance'] = database[user]['balance'] - amount
    print("Transaction successful!")

def deposit(user):
  amount = int(input('Enter amount to deposit'))
  database[user]['balance'] = database[user]['balance'] + amount
  print("Transaction successful!")

def viewBalance(user):
  print('Your balance is {} INR'.format(database[user]['balance']))

def passwordChange(user, email):
  while email != database[user]['email']:
    email = input('Enter your correct email ID:')
  database[user]['password'] = input('Choose your new password: ')
  print('Password changed! Now login please!')

def option():
    input(
        '''
        Choose the following options:
        0. Exit
        1. Deposit
        2. Withdraw
        3. View Balance
        4. Change Password
        '''
    )

def main():
  input('''
      Choose one of the options:
      1. Login 
      2. Sign Up
      0. Exit
     ''')

num = int(main())

while num != 0:

  if num == 1:
    username = input('Enter username: ')
    password = input('Enter Password: ')
    user = login(username, password)
    choice = int(option())
    while choice != 0:
      if choice == 1:
        deposit(user)
      elif choice == 2:
        withdrawal(user)
      elif choice == 3:
        viewBalance(user)
      elif choice == 4:
        email = input('Enter you email: ')
        passwordChange(user, email)

      choice = int(option())      


  elif num == 2:
    signUp()

  num = int(main())

